### ISSUE TITLE
[Assignment] 2주차 과제

### ISSUE THREAD

**Issue by ryuchanghwi** [GO-SOPT-iOS-Part/RyuChanghwi#3]
## Description
- 2차 세미나 과제
- 이슈 설명

## To-do
- [x] 티빙 로그인 UI 구현
- [x] 티빙 홈 UI 구현
- [x] 닉네임 만들기 기능
- [x] 폰트 추가
- [x] 색상 추가
